# Generated by Django 5.0.6 on 2024-07-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_back", "0002_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="_id",
            new_name="id",
        ),
    ]
