# Generated by Django 5.0.6 on 2024-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_back", "0003_rename__id_movie_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="name",
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="name_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
