# Generated by Django 5.0.6 on 2024-07-23 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movie_back",
            "0004_remove_movie_name_movie_country_movie_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="owner",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
