# Generated by Django 5.0.6 on 2024-07-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_back", "0005_movie_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="name_en",
            new_name="nameEn",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="name_ru",
            new_name="nameRu",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="trailer_link",
            new_name="trailerLink",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="owner",
        ),
    ]
